# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f4dc4a34b585131c3f317006c7189853"
name = "shop-dashboard"
handle = "shop-dashboard-24"
application_url = "https://usc-variety-posters-consider.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_discounts,write_products"

[auth]
redirect_urls = ["https://usc-variety-posters-consider.trycloudflare.com/auth/callback", "https://usc-variety-posters-consider.trycloudflare.com/auth/shopify/callback", "https://usc-variety-posters-consider.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
