# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f4dc4a34b585131c3f317006c7189853"
name = "shop-dashboard"
handle = "shop-dashboard-24"
application_url = "https://nj-am-papers-aruba.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_orders"

[auth]
redirect_urls = ["https://nj-am-papers-aruba.trycloudflare.com/auth/callback", "https://nj-am-papers-aruba.trycloudflare.com/auth/shopify/callback", "https://nj-am-papers-aruba.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
